## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: hb-kafka-standard-4c8g3w

## @section Controller-eligible statefulset parameters
##
controller:
  ## @param controller.replicaCount Number of Kafka controller-eligible nodes
  ##
  replicaCount: 3
  ## @param controller.controllerOnly If set to true, controller nodes will be deployed as dedicated controllers, instead of controller+broker processes.
  ##
  controllerOnly: true
  ##
  ## @param controller.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  ##
  persistence:
    ## @param controller.persistence.enabled Enable Kafka data persistence using PVC
    ##
    enabled: true
    ## @param controller.persistence.size PVC Storage Request for Kafka data volume
    ##
    size: 32Gi

## @section Broker-only statefulset parameters
##
broker:
  ## @param broker.replicaCount Number of Kafka broker-only nodes
  ##
  replicaCount: 3
  ## @param broker.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 1Gi
  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  ##
  persistence:
    ## @param broker.persistence.enabled Enable Kafka data persistence using PVC
    ##
    enabled: true
    ## @param broker.persistence.size PVC Storage Request for Kafka data volume
    ##
    size: 256Gi
