name: "standard-2c6g32"
id: 3b3addda-c4fc-4a59-bbf5-0f640920e09f
description: "Opensearch standard-2c6g32 plan which limit resources 2 cores 6Gi memory and persistence size 32Gi."
displayName: "standard-2c6g32"
bindable: true
maximum_polling_duration: 1800
