name: "standard-2c4g20"
id: 2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e
description: "mongodb standard-2c4g20 plan: Disk 20Gi ,vCPUs 2 , RAM 4G "
displayName: "standard-2c4g20"
bindable: true
maximum_polling_duration: 1800
