name: "standard-20"
id: edf8bdfe-b1dc-4f41-b042-801153794df7
description: "Mysql Cluster standard-20 plan: Disk 20Gi ,vCPUs 2 , RAM 4G , DB MAX Connection 1000"
displayName: "standard-20"
bindable: true
maximum_polling_duration: 1800
