name: airflow
version: 2
id: 15032a52-33c2-4b40-97aa-ceb972f51509
description: "airflow."
displayName: "airflow"
metadata:
  displayName: "airflow"
  provider:
    name: drycc
    supportURL: http://airflow.apache.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/airflow
tags: airflow
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "timezone"
  required: false
  description: "timezone config for values.yaml"
- name: "auth.password"
  required: false
  description: "auth.password config for values.yaml"
- name: "git"
  required: false
  description: "git config for values.yaml"
- name: "master.image"
  required: false
  description: "master image config for values.yaml"
- name: "scheduler.image"
  required: false
  description: "scheduler image config for values.yaml"
- name: "worker.image"
  required: false
  description: "worker image config for values.yaml"
- name: "worker.persistence"
  required: false
  description: "worker persistence config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "statsd.enable"
  required: false
  description: "statsd enable or not config for values.yaml"
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "externalDatabase"
  required: true
  description: "externalDatabase config for values.yaml"
- name: celeryBrokerUrl
  required: true
  description: "celeryBrokerUrl config for values.yaml"
- name: celeryBrokerTransportOption
  required: false
  description: "celeryBrokerTransportOption config for values.yaml"
archive: false
