name: "standard-v4s20"
id: 3e0da1bf-21fd-4ac4-a655-2c7a3e6e1428
description: "Seaweedfs standard-v4s20 plan which limit 4 volumes, each size 20G."
displayName: "standard-v4s20"
bindable: true
maximum_polling_duration: 1800
