{{- /*
Copyright Drycc Community.
SPDX-License-Identifier: APACHE-2.0
*/}}
{{- if (include "patroni.createCronJob" .) }}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ include "patroni.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    application: {{ template "patroni.fullname" . }}
    cluster-name: {{ template "patroni.fullname" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

spec:
  schedule: "{{ .Values.backup.scheduleCronJob }}"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure              
          containers:         
          - name: {{ .Chart.Name }}-backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
            command:  
              - /usr/bin/env
              - bash
              - -c
              - |
                curl "http://${REPLHOST}:9000/pg_backup"
            env:
            - name: REPLHOST
              value: {{ include "patroni.fullname" . }}-repl
{{- end -}}