name: zookeeper
version: 1.1.0
id: b50db3b5-8d5f-4be9-b8bd-467ecd6cc11d
description: "zookeeper."
displayName: "zookeeper"
metadata:
  displayName: "zookeeper"
  provider:
    name: drycc
    supportURL: https://zookeeper.apache.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/zookeeper
tags: zookeeper
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
