name: kafka
version: 3.6
id: 412e368f-bf78-4798-92cc-43343119a57d
description: "kafka."
displayName: "kafka"
metadata:
  displayName: "kafka"
  provider:
    name: drycc
    supportURL: https://kafka.apache.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/kafka
tags: kafka
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "extraEnvVars"
  required: false
  description: "extraEnvVars config for values.yaml"
- name: "extraConfig"
  required: false
  description: "extraConfig config for values.yaml"
- name: "controller.extraConfig"
  required: false
  description: "controller.extraConfig config for values.yaml"
- name: "controller.nodeSelector"
  required: false
  description: "controller.nodeSelector config for values.yaml"
- name: "broker.extraConfig"
  required: false
  description: "broker.extraConfig config for values.yaml"
- name: "broker.nodeSelector"
  required: false
  description: "broker.nodeSelector config for values.yaml"
- name: "listeners.client.protocol"
  required: false
  description: "listeners client protocol config for values.yaml"
- name: "listeners.controller.protocol"
  required: false
  description: "listeners controller protocol config for values.yaml"
- name: "listeners.interbroker.protocol"
  required: false
  description: "listeners interbroker protocol config for values.yaml"
- name: "listeners.external.protocol"
  required: false
  description: "listeners external protocol config for values.yaml"
- name: "sasl"
  required: false
  description: "sasl config for values.yaml"
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "externalAccess.enabled"
  required: false
  description: "externalAccess enabled or not config for values.yaml"
- name: "listeners.advertisedListeners"
  required: false
  description: "listeners advertisedListeners or not config for values.yaml"
- name: "metrics.jmx.enabled"
  required: false
  description: "metrics jmx enabled or not config for values.yaml"
- name: "metrics.nodeSelector"
  required: false
  description: "metrics nodeSelector config for values.yaml"
- name: "metrics.kafka.enabled"
  required: false
  description: "metrics kafka enabled or not config for values.yaml"
archive: false
