name: minio
version: 2023
id: ea2a9b87-fbc4-4e2a-adee-161c1f91d98d
description: "minio."
displayName: "minio"
metadata:
  displayName: "minio"
  provider:
    name: drycc
    supportURL: https://min.io
  documentationURL: https://github.com/drycc-addons/drycc-docker-minio
tags: minio
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "metrics.enabled"
  required: false
  description: "metrics enabled or not config for values.yaml"
archive: false
