apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}-repl
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: patroni
    application: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "patroni.fullname" . }}
    role: replica
spec:
  type: {{ .Values.service.type }}
  selector:
    application: {{ template "patroni.fullname" . }}
    cluster-name: {{ template "patroni.fullname" . }}
    role: replica
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  - name: pgbackup
    port: 9000
    targetPort: 9000