name: etcd-3.6
version: "3.6"
id: 74c7112f-bd4a-4ecf-bfec-ca9443b4815a
description: "A distributed, reliable key-value store for the most critical data of a distributed system"
displayName: "etcd-3.6"
metadata:
  displayName: "etcd-3.6"
  provider:
    name: drycc
    supportURL: https://etcd.io/
  documentationURL: https://etcd.io/
tags: etcd
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "extraDeploy"
  required: false
  description: "extraDeploy config for values.yaml"
- name: "nodeSelector"
  required: false
  description: "nodeSelector config for values.yaml"
- name: "auth"
  required: false
  description: "auth config for values.yaml"
- name: "maxProcs"
  required: false
  description: "maxProcs config for values.yaml"
- name: "configuration"
  required: false
  description: "configuration config for values.yaml"
- name: "extraEnvVars"
  required: false
  description: "extraEnvVars config for values.yaml"
- name: "externalTrafficPolicy"
  required: false
  description: "externalTrafficPolicy config for values.yaml"
- name: "persistence"
  required: false
  description: "persistence config for values.yaml"
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "startFromSnapshot"
  required: false
  description: "startFromSnapshot config for values.yaml"
- name: "disasterRecovery"
  required: false
  description: "disasterRecovery config for values.yaml"
- name: "preUpgradeJob"
  required: false
  description: "preUpgradeJob config for values.yaml"
- name: "defrag"
  required: false
  description: "defrag config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "metrics.enabled"
  required: false
  description: "metrics enabled or not config for values.yaml"
archive: false
