name: "standard-1000m"
id: ac2300db-f5ac-413e-a663-dd13da2034b0
description: "Fluentbit standard-100m plan: vCPUs 1000m, RAM 1G"
displayName: "standard-1000m"
bindable: true
maximum_polling_duration: 1800
