{{- /*
Copyright Drycc Community.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  {{- if eq .Values.router.service.type "ClusterIP" }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: {{ .Values.router.service.portrw }}
      - port: {{ .Values.router.service.portro }}
      - port: 24901
      - port: 33061
      - port: 6446
      - port: 6447
    {{- if and .Values.metrics.enabled }}
      - port: {{ .Values.metrics.service.port }}
    {{- end }} 
    {{- if or .Values.networkPolicy.allowCurrentNamespace .Values.networkPolicy.allowNamespaces }}
      from:
      {{- if .Values.networkPolicy.allowCurrentNamespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      {{- end }}
      {{- range $namespace := .Values.networkPolicy.allowNamespaces }}
        {{- if $namespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.router.service.type "LoadBalancer" }}
  ingress:
    - {}
  {{- end}}
{{- end }}
