name: redis
version: 1.1.0
id: e1fd0d37-9046-4152-a29b-d155c5657c8b
description: "redis."
displayName: "redis"
metadata:
  displayName: "redis"
  provider:
    name: drycc
    supportURL: http://redis.io/
  documentationURL: https://github.com/drycc-adons/drycc-docker-redis
tags: redis
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
