name: "standard-32c128g800"
id: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d
description: "mongodb standard-32c128g800 plan: Disk 800Gi ,vCPUs 32 , RAM 128G "
displayName: "standard-32c128g800"
bindable: true
maximum_polling_duration: 1800
