name: opensearch
version: "2.10"
id: 5975094d-45cc-4e85-8573-f93937d026c7
description: "opensearch."
displayName: "opensearch"
metadata:
  displayName: "opensearch"
  provider:
    name: drycc
    supportURL: https://opensearch.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/opensearch
tags: opensearch
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "master.networkPolicy.allowNamespaces"
  required: false
  description: "master networkPolicy allowNamespaces config for values.yaml"
- name: "ingest.networkPolicy.allowNamespaces"
  required: false
  description: "ingest networkPolicy allowNamespaces config for values.yaml"
- name: "data.networkPolicy.allowNamespaces"
  required: false
  description: "data networkPolicy allowNamespaces config for values.yaml"
- name: "coordinating.networkPolicy.allowNamespaces"
  required: false
  description: "coordinating networkPolicy allowNamespaces config for values.yaml"
- name: "dashboards.networkPolicy.allowNamespaces"
  required: false
  description: "dashboards networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "dashboards.service.type"
  required: false
  description: "dashboards service type config for values.yaml"
archive: false
