name: "standard-400"
id: 16bfd3a8-1080-4731-93d0-bd90e6ba6dad
description: "PostgreSQL Cluster standard-400 plan: Disk 400Gi ,vCPUs 16 , RAM 64G , DB MAX Connection 2000"
displayName: "standard-400"
bindable: true
maximum_polling_duration: 1800
