name: cloudbeaver
version: 23
id: b7cb26a4-b258-445c-860b-a664239a67f8
description: "cloudbeaver"
displayName: "cloudbeaver"
metadata:
  displayName: "cloudbeaver"
  provider:
    name: drycc
    supportURL: http://cloudbeaver.io/
  documentationURL: https://github.com/drycc-addons/
tags: cloudbeaver
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: false
allow_parameters:
- name: "service.type"
  description: "service type config for values.yaml"
archive: false
