name: "standard-200"
id: a2160ac2-6c35-4162-b8a2-8dfb2e01816f
description: "PostgreSQL Cluster standard-200 plan: Disk 200Gi ,vCPUs 8 , RAM 32G , DB MAX Connection 2000"
displayName: "standard-200"
bindable: true
maximum_polling_duration: 1800
