name: flink
version: 1.17
id: 9ce3c3ba-33b5-4e4e-a5e9-a338a83d5070
description: "flink"
displayName: "flink"
metadata:
  displayName: "flink"
  provider:
    name: drycc
    supportURL: https://flink.apache.org/
  documentationURL: https://flink.apache.org/
tags: flink
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "jobmanager.nodeSelector"
  required: false
  description: "jobmanager nodeSelector config for values.yaml"
- name: "jobmanager.service.type"
  required: false
  description: "jobmanager service type config for values.yaml"
- name: "jobmanager.networkPolicy.allowNamespaces"
  required: false
  description: "jobmanager networkPolicy allowNamespaces config for values.yaml"
- name: "jobmanager.extraEnvVars"
  required: false
  description: "jobmanager extraEnvVars config for values.yaml"
- name: "taskmanager.nodeSelector"
  required: false
  description: "taskmanager nodeSelector config for values.yaml"
- name: "taskmanager.service.type"
  required: false
  description: "taskmanager service type config for values.yaml"
- name: "taskmanager.networkPolicy.allowNamespaces"
  required: false
  description: "taskmanager networkPolicy allowNamespaces config for values.yaml"
- name: "taskmanager.extraEnvVars"
  required: false
  description: "taskmanager extraEnvVars config for values.yaml"
- name: "taskmanager.persistence.size"
  required: false
  description: "taskmanager persistence size config for values.yaml"
archive: false
