name: "standard-16c64g400"
id: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c
description: "mongodb standard-16c64g400 plan: Disk 400Gi ,vCPUs 16 , RAM 64G "
displayName: "standard-16c64g400"
bindable: true
maximum_polling_duration: 1800
