## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: "hb-redis-cluster-standard-65536"

## io-thread
ioThread:
  enabled: true
  doReads:  "yes"
  counts: 2

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.path Path to mount the volume at, to use other images Redis&reg; images.
  ##
  path: /drycc/redis/data
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Size of data volume
  ##
  size: 128Gi

## @section Redis&reg; statefulset parameters
##

redis:
  ## Redis&reg; resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param redis.resources.limits The resources limits for the container
  ## @param redis.resources.requests The requested resources for the container
  ##
  resources:
    limits:
      cpu: 4
      memory: 64Gi
    requests:
      cpu: 1
      memory: 8Gi

## @section Proxy&reg; statefulset parameters
##
proxy:
  ## max-procs
  maxProcs: 4
  ## backend-init-connections
  backendInitConnections: 10
  ## backend-idle-connections
  backendIdleConnections: 300
  ## Proxy&reg; resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param proxy.resources.limits The resources limits for the container
  ## @param proxy.resources.requests The requested resources for the container
  ##
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
