name: zookeeper
version: 3.9
id: b50db3b5-8d5f-4be9-b8bd-467ecd6cc11d
description: "zookeeper."
displayName: "zookeeper"
metadata:
  displayName: "zookeeper"
  provider:
    name: drycc
    supportURL: https://zookeeper.apache.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/zookeeper
tags: zookeeper
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "nodeSelector"
  required: false
  description: "nodeSelector config for values.yaml"
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
- name: "metrics.enabled"
  required: false
  description: "metrics enabled or not config for values.yaml"
archive: false
