name: "standard-4c16g100"
id: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a
description: "mongodb standard-4c16g100 plan: Disk 100Gi ,vCPUs c , RAM 16G "
displayName: "standard-4c16g100"
bindable: true
maximum_polling_duration: 1800
