name: spark
version: 3.4
id: 4aea5c0f-9495-420d-896a-ffc61a3eced5
description: "spark."
displayName: "spark"
metadata:
  displayName: "spark"
  provider:
    name: drycc
    supportURL: https://spark.apache.org/
  documentationURL: https://github.com/drycc-addons/containers/tree/main/containers/spark
tags: spark
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "networkPolicy.allowNamespaces"
  description: "networkPolicy allowNamespaces config for values.yaml"
archive: false
