name: clickhouse-basic
version: 26
<<<<<<< HEAD
id: a7c11ea2-ec46-4631-a589-36b8ea672969
=======
id: e711a9ec-4ffd-4392-b04d-ca07b481f434
>>>>>>> b8a5d6ca0425fb204871eb07999bb9b91375409b
description: "clickhouse-basic"
displayName: "clickhouse-basic"
metadata:
  displayName: "clickhouse-basic"
  provider:
    name: drycc
    supportURL: http://clickhouse.io/
  documentationURL: https://github.com/drycc-addons/
tags: clickhouse
bindable: true
instances_retrievable: true
bindings_retrievable: true
plan_updateable: true
allow_parameters:
- name: "networkPolicy.allowNamespaces"
  required: false
  description: "networkPolicy allowNamespaces config for values.yaml"
- name: "service.type"
  required: false
  description: "service type config for values.yaml"
archive: false
