name: "standard-4c16g100"
id: 050af00e-fc0e-49d3-a1d1-66f8c67dda3a
description: "Mysql Cluster standard-4c16g100 plan: Disk 100Gi ,vCPUs 4 , RAM 16G , DB MAX Connection 4000"
displayName: "standard-4c16g100"
bindable: true
maximum_polling_duration: 1800
