name: "standard-4c12g128"
id: 5c895b68-426c-4ff3-81d1-3dabda94122f
description: "Opensearch standard-4c12g128 plan which limit resources 4 cores 12Gi memory and persistence size 128Gi."
displayName: "standard-4c12g128"
bindable: true
maximum_polling_duration: 1800
